---
- hosts: '{{ host }}'
  user: olimpus
  gather_facts: no
  strategy: free
  tasks:
  - name: Load All Selected User YAML
    include_vars:
      dir: 'user/{{ host }}'
      ignore_unknown_extensions: True
      extensions: [yaml]
    when: username is not defined

  - name: Load Devops User YAML
    include_vars:
      dir: user/devops
      ignore_unknown_extensions: True
      extensions: [yaml]
    when: username is not defined

  - name: Load user by Username and Role
    include_vars:
      dir: 'user/{{ host }}'
      files_matching: '{{ username }}.yaml'
    when: username is defined

  - name: Add users | create users, shell, home dirs
    user: name={{ item.username }} shell=/bin/bash createhome=yes groups={{ item.groups }} comment='create with ansible'
    become: yes
    with_items: '{{users}}'

  - name: Setup | authorized key upload
    authorized_key: user={{ item.username }}
      key="{{ lookup('file', 'pub_key/{{ item.username }}.pub') }}"
    become: yes
    with_items: '{{users}}'

  - name: Sudoers | update sudoers file and validate
    lineinfile: "dest=/etc/sudoers.d/{{ item.username }}
      insertafter=EOF
      line='{{ item.username }} ALL=(ALL) NOPASSWD: ALL'
      regexp='^{{ item.username }} .*'
      state=present create=yes"
    when: 'item.use_sudo == True'
    become: yes
    with_items: '{{users}}'

  - name: Export histotime to every user
    lineinfile:
      path: /home/{{ item.username }}/.bash_profile
      line: 'export HISTTIMEFORMAT="%d/%m/%y %T "'
      state: present
    become: yes
    with_items: '{{users}}'
